-- Additive closure/reopen history for the Exits dashboard. Run after Phase 2,
-- while the old reporting lifecycle source still exists. Safe to rerun.
-- Stop the lean scraper while applying this upgrade and its application code.
BEGIN;

CREATE TABLE IF NOT EXISTS lean.listing_lifecycle_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id bigint NOT NULL REFERENCES lean.listings(article_id),
  event_type text NOT NULL CHECK (event_type IN ('closed', 'reopened')),
  occurred_at timestamptz NOT NULL,
  opened_at timestamptz,
  price numeric(12,2),
  deal text CHECK (deal IN ('sale', 'rent', 'unknown')),
  property_type text,
  neighborhood text,
  sqm numeric(8,2),
  rooms text,
  latitude double precision,
  longitude double precision,
  title text,
  url text,
  UNIQUE (article_id, event_type, occurred_at)
);
CREATE INDEX IF NOT EXISTS lean_listing_lifecycle_events_closed_idx
  ON lean.listing_lifecycle_events (occurred_at DESC, deal, property_type, neighborhood)
  WHERE event_type = 'closed';
CREATE INDEX IF NOT EXISTS lean_listing_lifecycle_events_article_idx
  ON lean.listing_lifecycle_events (article_id, occurred_at DESC, id DESC);

-- Rebuild all known historical cycles from the old event-backed source, not
-- the refreshable OLAP mart, which can lag behind the scraper. A closed cycle
-- remains in this table even if the listing was reopened later.
INSERT INTO lean.listing_lifecycle_events
  (article_id, event_type, occurred_at, opened_at, price, deal, property_type,
   neighborhood, sqm, rooms, latitude, longitude, title, url)
SELECT c.article_id, 'closed', c.closed_at, c.opened_at, c.final_asking_price,
       c.closing_deal, c.closing_property_type, c.closing_neighborhood,
       c.closing_sqm, c.closing_rooms,
       p.latitude, p.longitude, p.title, p.url
  FROM reporting.lifecycle_cycles_source c
  JOIN lean.listings l ON l.article_id = c.article_id
  LEFT JOIN public.listings p ON p.article_id = c.article_id
 WHERE c.closed_at IS NOT NULL
ON CONFLICT (article_id, event_type, occurred_at) DO NOTHING;

INSERT INTO lean.listing_lifecycle_events
  (article_id, event_type, occurred_at, opened_at, price, deal, property_type,
   neighborhood, sqm, rooms, latitude, longitude, title, url)
SELECT c.article_id, 'reopened', c.opened_at, NULL, NULL,
       c.opening_deal, c.opening_property_type, c.opening_neighborhood,
       c.opening_sqm, c.opening_rooms,
       p.latitude, p.longitude, p.title, p.url
  FROM reporting.lifecycle_cycles_source c
  JOIN lean.listings l ON l.article_id = c.article_id
  LEFT JOIN public.listings p ON p.article_id = c.article_id
 WHERE c.cycle_no > 1
ON CONFLICT (article_id, event_type, occurred_at) DO NOTHING;

-- The legacy current row covers a rare closure absent from reconstructed
-- history. It also retains pre-cutover closure state for a listing which the
-- one-shot lean run has already reopened.
INSERT INTO lean.listing_lifecycle_events
  (article_id, event_type, occurred_at, opened_at, price, deal, property_type,
   neighborhood, sqm, rooms, latitude, longitude, title, url)
SELECT p.article_id, 'closed', p.closed_at, p.first_seen, p.closing_price,
       CASE WHEN p.is_rent THEN 'rent' ELSE 'sale' END,
       coalesce(p.closing_category, l.property_type),
       coalesce(nullif(p.location, ''), l.neighborhood),
       p.sqm, p.rooms, p.latitude, p.longitude, p.title, p.url
  FROM public.listings p
  JOIN lean.listings l ON l.article_id = p.article_id
 WHERE p.closed_at IS NOT NULL
ON CONFLICT (article_id, event_type, occurred_at) DO NOTHING;

-- A lean-only reopen before this upgrade is visible as an old closed row
-- followed by a newer lean sighting. The exact first sighting was not stored
-- by the original lean writer, so last_seen is the available approximation.
INSERT INTO lean.listing_lifecycle_events
  (article_id, event_type, occurred_at, opened_at, price, deal, property_type,
   neighborhood, sqm, rooms, latitude, longitude, title, url)
SELECT l.article_id, 'reopened', l.last_seen, NULL, l.price,
       l.deal, l.property_type, l.neighborhood,
       l.sqm, l.rooms, l.latitude, l.longitude, l.title, l.url
  FROM lean.listings l
  JOIN public.listings p ON p.article_id = l.article_id
 WHERE p.closed_at IS NOT NULL
   AND l.last_seen > p.closed_at
   AND (l.closed_at IS NULL OR l.closed_at > p.closed_at)
   AND NOT EXISTS (
     SELECT 1 FROM lean.listing_lifecycle_events e
      WHERE e.article_id = l.article_id
        AND e.event_type = 'reopened'
        AND e.occurred_at > p.closed_at
   )
ON CONFLICT (article_id, event_type, occurred_at) DO NOTHING;

-- Capture the lean-only closures since backfill. Existing historical rows
-- win when their timestamp matches, preserving the event-time dimensions.
INSERT INTO lean.listing_lifecycle_events
  (article_id, event_type, occurred_at, opened_at, price, deal, property_type,
   neighborhood, sqm, rooms, latitude, longitude, title, url)
SELECT l.article_id, 'closed', l.closed_at,
       coalesce((SELECT max(e.occurred_at)
                   FROM lean.listing_lifecycle_events e
                  WHERE e.article_id = l.article_id
                    AND e.event_type = 'reopened'
                    AND e.occurred_at < l.closed_at), l.first_seen),
       l.closing_price, l.deal, l.property_type, l.neighborhood,
       l.sqm, l.rooms, l.latitude, l.longitude, l.title, l.url
  FROM lean.listings l
 WHERE l.closed_at IS NOT NULL
ON CONFLICT (article_id, event_type, occurred_at) DO NOTHING;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'olx_app') THEN
    GRANT USAGE ON SCHEMA lean TO olx_app;
    GRANT SELECT, INSERT ON lean.listing_lifecycle_events TO olx_app;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA lean TO olx_app;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'olx_reporting') THEN
    GRANT USAGE ON SCHEMA lean TO olx_reporting;
    GRANT SELECT ON lean.listing_lifecycle_events TO olx_reporting;
  END IF;
END $$;

COMMIT;
