-- Preserve the logical raw-response and page-manifest history in lean.
-- Run only after Phase 5 validation, with all writers stopped and a fresh
-- verified backup available. Safe to rerun before lean archive writes begin.
BEGIN ISOLATION LEVEL REPEATABLE READ;

CREATE TABLE IF NOT EXISTS lean.raw_api_responses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id bigint REFERENCES lean.scrape_runs(id) ON DELETE SET NULL,
  article_id bigint REFERENCES lean.listings(article_id) ON DELETE SET NULL,
  request_kind text NOT NULL CHECK (request_kind IN ('search', 'detail')),
  request_url text NOT NULL,
  fetched_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT 'infinity'::timestamptz,
  parser_version text NOT NULL,
  payload jsonb,
  source_payload jsonb,
  request_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  response_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  build_version text NOT NULL DEFAULT 'unknown',
  diagnostic jsonb,
  archive_format text NOT NULL DEFAULT 'canonical-v2'
    CHECK (archive_format IN ('canonical-v2', 'diagnostic-v2'))
);
CREATE INDEX IF NOT EXISTS lean_raw_api_responses_stream_idx
  ON lean.raw_api_responses (request_kind, request_url, fetched_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS lean_raw_api_responses_expiry_idx
  ON lean.raw_api_responses (expires_at) WHERE expires_at <> 'infinity';
CREATE INDEX IF NOT EXISTS lean_raw_api_responses_article_idx
  ON lean.raw_api_responses (article_id, fetched_at DESC) WHERE article_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS lean.scrape_run_pages (
  run_id bigint NOT NULL REFERENCES lean.scrape_runs(id) ON DELETE CASCADE,
  page_number integer NOT NULL CHECK (page_number > 0),
  attempt integer NOT NULL DEFAULT 1 CHECK (attempt > 0),
  fetched_at timestamptz NOT NULL DEFAULT now(),
  request_url text NOT NULL,
  response_state text NOT NULL CHECK (
    response_state IN ('ok', 'verified_empty', 'malformed', 'blocked', 'error')
  ),
  expected_total integer CHECK (expected_total IS NULL OR expected_total >= 0),
  expected_last_page integer CHECK (expected_last_page IS NULL OR expected_last_page > 0),
  response_page integer CHECK (response_page IS NULL OR response_page > 0),
  response_per_page integer CHECK (response_per_page IS NULL OR response_per_page > 0),
  raw_item_count integer NOT NULL DEFAULT 0 CHECK (raw_item_count >= 0),
  parsed_item_count integer NOT NULL DEFAULT 0 CHECK (parsed_item_count >= 0),
  duplicate_item_count integer NOT NULL DEFAULT 0 CHECK (duplicate_item_count >= 0),
  parse_rejection_count integer NOT NULL DEFAULT 0 CHECK (parse_rejection_count >= 0),
  parse_rejections jsonb NOT NULL DEFAULT '[]'::jsonb,
  error text,
  is_authoritative boolean NOT NULL DEFAULT false,
  PRIMARY KEY (run_id, page_number, attempt)
);
CREATE INDEX IF NOT EXISTS lean_scrape_run_pages_latest_idx
  ON lean.scrape_run_pages (run_id, page_number, attempt DESC);
CREATE INDEX IF NOT EXISTS lean_scrape_run_pages_state_idx
  ON lean.scrape_run_pages (response_state, fetched_at DESC);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM public.raw_api_responses s
     WHERE (s.run_id IS NOT NULL AND NOT EXISTS
              (SELECT 1 FROM lean.scrape_runs r WHERE r.id = s.run_id))
        OR (s.article_id IS NOT NULL AND NOT EXISTS
              (SELECT 1 FROM lean.listings l WHERE l.article_id = s.article_id))
  ) THEN
    RAISE EXCEPTION 'raw response archive has run/listing IDs missing from lean';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.scrape_run_pages s
     WHERE NOT EXISTS (SELECT 1 FROM lean.scrape_runs r WHERE r.id = s.run_id)
  ) THEN
    RAISE EXCEPTION 'scrape page history has run IDs missing from lean';
  END IF;
END $$;

INSERT INTO lean.raw_api_responses
  (id, run_id, article_id, request_kind, request_url, fetched_at, expires_at,
   parser_version, payload, source_payload, request_metadata, response_metadata,
   build_version, diagnostic, archive_format)
OVERRIDING SYSTEM VALUE
SELECT id, run_id, article_id, request_kind, request_url, fetched_at, expires_at,
       parser_version, payload, source_payload, request_metadata, response_metadata,
       build_version, diagnostic, archive_format
  FROM public.raw_api_responses
ON CONFLICT (id) DO NOTHING;

INSERT INTO lean.scrape_run_pages
  (run_id, page_number, attempt, fetched_at, request_url, response_state,
   expected_total, expected_last_page, response_page, response_per_page,
   raw_item_count, parsed_item_count, duplicate_item_count,
   parse_rejection_count, parse_rejections, error, is_authoritative)
SELECT run_id, page_number, attempt, fetched_at, request_url, response_state,
       expected_total, expected_last_page, response_page, response_per_page,
       raw_item_count, parsed_item_count, duplicate_item_count,
       parse_rejection_count, parse_rejections, error, is_authoritative
  FROM public.scrape_run_pages
ON CONFLICT (run_id, page_number, attempt) DO NOTHING;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM public.raw_api_responses s
      LEFT JOIN lean.raw_api_responses d USING (id)
     WHERE d.id IS NULL OR to_jsonb(s) IS DISTINCT FROM to_jsonb(d)
  ) THEN
    RAISE EXCEPTION 'raw response archive migration mismatch';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.scrape_run_pages s
      LEFT JOIN lean.scrape_run_pages d USING (run_id, page_number, attempt)
     WHERE d.run_id IS NULL OR to_jsonb(s) IS DISTINCT FROM to_jsonb(d)
  ) THEN
    RAISE EXCEPTION 'scrape page history migration mismatch';
  END IF;
END $$;

SELECT setval(
  pg_get_serial_sequence('lean.raw_api_responses', 'id'),
  COALESCE(max(id), 1),
  count(*) > 0
) FROM lean.raw_api_responses;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'olx_app') THEN
    GRANT SELECT, INSERT, DELETE ON lean.raw_api_responses TO olx_app;
    GRANT SELECT, INSERT ON lean.scrape_run_pages TO olx_app;
    GRANT USAGE, SELECT ON SEQUENCE lean.raw_api_responses_id_seq TO olx_app;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'olx_reporting') THEN
    GRANT SELECT ON lean.scrape_run_pages TO olx_reporting;
  END IF;
END $$;

COMMIT;
