-- Phase 1: additive schema only. Run after the pre-migration pg_dump.
-- PostgreSQL 15+ and PostGIS are required (the current deployment uses PG 18).
BEGIN;

CREATE SCHEMA lean;

CREATE TABLE lean.neighborhoods (
  name text PRIMARY KEY,
  boundary public.geometry(MultiPolygon, 4326) NOT NULL
);
CREATE INDEX lean_neighborhoods_boundary_gist ON lean.neighborhoods USING gist (boundary);

CREATE TABLE lean.saved_searches (
  search_key text PRIMARY KEY,
  name text NOT NULL,
  url text NOT NULL,
  category text,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_scraped_at timestamptz,
  listing_count integer,
  median_ppm2 integer,
  new_count integer,
  drop_count integer
);

CREATE TABLE lean.listings (
  article_id bigint PRIMARY KEY,
  url text NOT NULL,
  title text NOT NULL,
  deal text NOT NULL CHECK (deal IN ('sale', 'rent')),
  property_type text,
  sqm numeric(8,2),
  rooms text,
  price numeric(12,2),
  price_text text,
  currency text NOT NULL DEFAULT 'BAM',
  ppm2 integer,
  neighborhood text REFERENCES lean.neighborhoods(name),
  latitude double precision,
  longitude double precision,
  seller_type text,
  condition text,
  parking boolean,
  elevator boolean,
  floor_num smallint,
  year_built smallint,
  extra jsonb NOT NULL DEFAULT '{}'::jsonb,
  search_keys text[] NOT NULL DEFAULT '{}'::text[],
  first_seen timestamptz NOT NULL DEFAULT now(),
  last_seen timestamptz NOT NULL DEFAULT now(),
  closed_at timestamptz,
  closing_price numeric(12,2),
  published_at timestamptz,
  renewed_at timestamptz,
  details_fetched_at timestamptz,
  last_enrichment_attempted_at timestamptz,
  api_status text
);
CREATE INDEX lean_listings_active_filter_idx
  ON lean.listings (deal, property_type, neighborhood, rooms)
  WHERE closed_at IS NULL;
CREATE INDEX lean_listings_price_idx
  ON lean.listings (deal, price) WHERE closed_at IS NULL;
CREATE INDEX lean_listings_geo_idx
  ON lean.listings (latitude, longitude) WHERE latitude IS NOT NULL;
CREATE INDEX lean_listings_search_keys_idx ON lean.listings USING gin (search_keys);

CREATE TABLE lean.price_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id bigint NOT NULL REFERENCES lean.listings(article_id),
  observed_at timestamptz NOT NULL DEFAULT now(),
  price numeric(12,2),
  currency text NOT NULL DEFAULT 'BAM',
  source text NOT NULL DEFAULT 'search'
);
CREATE INDEX lean_price_history_article_idx
  ON lean.price_history (article_id, observed_at DESC);

-- Persistent closure/reopen events keep every exit after a later reopening.
CREATE TABLE lean.listing_lifecycle_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id bigint NOT NULL REFERENCES lean.listings(article_id),
  event_type text NOT NULL CHECK (event_type IN ('closed', 'reopened')),
  occurred_at timestamptz NOT NULL,
  opened_at timestamptz,
  price numeric(12,2),
  deal text CHECK (deal IN ('sale', 'rent', 'unknown')),
  property_type text,
  neighborhood text,
  sqm numeric(8,2),
  rooms text,
  latitude double precision,
  longitude double precision,
  title text,
  url text,
  UNIQUE (article_id, event_type, occurred_at)
);
CREATE INDEX lean_listing_lifecycle_events_closed_idx
  ON lean.listing_lifecycle_events (occurred_at DESC, deal, property_type, neighborhood)
  WHERE event_type = 'closed';
CREATE INDEX lean_listing_lifecycle_events_article_idx
  ON lean.listing_lifecycle_events (article_id, occurred_at DESC, id DESC);

CREATE TABLE lean.scrape_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  search_key text REFERENCES lean.saved_searches(search_key),
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  pages integer,
  cards integer,
  status text NOT NULL DEFAULT 'running',
  error text,
  is_complete boolean NOT NULL DEFAULT false,
  failure_reason text,
  truncation_reason text
);

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'olx_app') THEN
    GRANT USAGE ON SCHEMA lean TO olx_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON
      lean.neighborhoods, lean.saved_searches, lean.listings,
      lean.price_history, lean.scrape_runs TO olx_app;
    GRANT SELECT, INSERT ON lean.listing_lifecycle_events TO olx_app;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA lean TO olx_app;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'olx_reporting') THEN
    GRANT USAGE ON SCHEMA lean TO olx_reporting;
    GRANT SELECT ON ALL TABLES IN SCHEMA lean TO olx_reporting;
  END IF;
END $$;

COMMIT;
