-- Complete lean schema for a fresh database.
-- PostgreSQL 15+ and PostGIS are required (the current deployment uses PG 18).
BEGIN;

CREATE SCHEMA lean;

CREATE TABLE lean.neighborhoods (
  name text PRIMARY KEY,
  boundary public.geometry(MultiPolygon, 4326) NOT NULL
);
CREATE INDEX lean_neighborhoods_boundary_gist ON lean.neighborhoods USING gist (boundary);

CREATE TABLE lean.saved_searches (
  search_key text PRIMARY KEY,
  name text NOT NULL,
  url text NOT NULL,
  category text,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_scraped_at timestamptz,
  listing_count integer,
  median_ppm2 integer,
  new_count integer,
  drop_count integer
);

CREATE TABLE lean.listings (
  article_id bigint PRIMARY KEY,
  url text NOT NULL,
  title text NOT NULL,
  deal text NOT NULL CHECK (deal IN ('sale', 'rent')),
  property_type text,
  sqm numeric(8,2),
  rooms text,
  price numeric(12,2),
  price_text text,
  currency text NOT NULL DEFAULT 'BAM',
  ppm2 integer,
  neighborhood text REFERENCES lean.neighborhoods(name),
  latitude double precision,
  longitude double precision,
  seller_type text,
  condition text,
  parking boolean,
  elevator boolean,
  floor_num smallint,
  year_built smallint,
  extra jsonb NOT NULL DEFAULT '{}'::jsonb,
  search_keys text[] NOT NULL DEFAULT '{}'::text[],
  first_seen date NOT NULL DEFAULT ((now() AT TIME ZONE 'Europe/Sarajevo')::date),
  last_seen timestamptz NOT NULL DEFAULT now(),
  closed_at date,
  closing_price numeric(12,2),
  published_at date,
  renewed_at date,
  details_fetched_at timestamptz,
  last_enrichment_attempted_at timestamptz,
  api_status text
);
CREATE INDEX lean_listings_active_filter_idx
  ON lean.listings (deal, property_type, neighborhood, rooms)
  WHERE closed_at IS NULL;
CREATE INDEX lean_listings_price_idx
  ON lean.listings (deal, price) WHERE closed_at IS NULL;
CREATE INDEX lean_listings_geo_idx
  ON lean.listings (latitude, longitude) WHERE latitude IS NOT NULL;
CREATE INDEX lean_listings_search_keys_idx ON lean.listings USING gin (search_keys);
CREATE INDEX lean_listings_first_seen_idx ON lean.listings (first_seen);

-- Publication and lifecycle evidence use Banja Luka calendar dates; scraper
-- operational clocks remain timestamps. Search observations are price markers.
CREATE TABLE lean.price_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id bigint NOT NULL REFERENCES lean.listings(article_id),
  price_date date NOT NULL DEFAULT ((now() AT TIME ZONE 'Europe/Sarajevo')::date),
  price numeric(12,2),
  currency text NOT NULL DEFAULT 'BAM',
  source text NOT NULL DEFAULT 'search'
);
CREATE UNIQUE INDEX lean_price_history_article_date_source_uidx
  ON lean.price_history (article_id, price_date DESC, source);
-- Cover daily API price windows while excluding search markers.
CREATE INDEX lean_price_history_api_article_date_idx
  ON lean.price_history (article_id, price_date)
  INCLUDE (price, currency)
  WHERE source = 'api_price_history';

-- Persistent closure/reopen events keep every exit after a later reopening.
-- The identity key preserves multiple transitions on the same calendar day.
CREATE TABLE lean.listing_lifecycle_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id bigint NOT NULL REFERENCES lean.listings(article_id),
  event_type text NOT NULL CHECK (event_type IN ('closed', 'reopened')),
  occurred_at date NOT NULL,
  opened_at date,
  price numeric(12,2),
  deal text CHECK (deal IN ('sale', 'rent', 'unknown')),
  property_type text,
  neighborhood text,
  sqm numeric(8,2),
  rooms text,
  latitude double precision,
  longitude double precision,
  title text,
  url text
);
CREATE INDEX lean_listing_lifecycle_events_closed_idx
  ON lean.listing_lifecycle_events (occurred_at DESC, deal, property_type, neighborhood)
  WHERE event_type = 'closed';
CREATE INDEX lean_listing_lifecycle_events_article_idx
  ON lean.listing_lifecycle_events (article_id, occurred_at DESC, id DESC);

CREATE TABLE lean.scrape_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  search_key text REFERENCES lean.saved_searches(search_key),
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  pages integer,
  cards integer,
  status text NOT NULL DEFAULT 'running',
  error text,
  is_complete boolean NOT NULL DEFAULT false,
  failure_reason text,
  truncation_reason text
);
CREATE INDEX lean_scrape_runs_started_at_idx
  ON lean.scrape_runs (started_at DESC);
CREATE INDEX lean_scrape_runs_search_latest_idx
  ON lean.scrape_runs (search_key, id DESC);
CREATE INDEX lean_scrape_runs_search_success_finished_idx
  ON lean.scrape_runs (search_key, finished_at DESC)
  WHERE status = 'ok' AND is_complete AND finished_at IS NOT NULL;
CREATE INDEX lean_scrape_runs_complete_success_idx
  ON lean.scrape_runs (finished_at DESC)
  WHERE status = 'ok' AND is_complete AND finished_at IS NOT NULL;

CREATE TABLE lean.raw_api_responses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id bigint REFERENCES lean.scrape_runs(id) ON DELETE SET NULL,
  article_id bigint REFERENCES lean.listings(article_id) ON DELETE SET NULL,
  request_kind text NOT NULL CHECK (request_kind IN ('search', 'detail')),
  request_url text NOT NULL,
  fetched_at timestamptz NOT NULL DEFAULT now(),
  parser_version text NOT NULL,
  payload jsonb,
  source_payload jsonb,
  request_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  response_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  build_version text NOT NULL DEFAULT 'unknown',
  diagnostic jsonb,
  archive_format text NOT NULL DEFAULT 'canonical-v2'
    CHECK (archive_format IN ('canonical-v2', 'diagnostic-v2'))
);
CREATE INDEX lean_raw_api_responses_stream_idx
  ON lean.raw_api_responses (request_kind, request_url, fetched_at DESC, id DESC);
CREATE INDEX lean_raw_api_responses_article_idx
  ON lean.raw_api_responses (article_id, fetched_at DESC) WHERE article_id IS NOT NULL;

CREATE TABLE lean.scrape_run_pages (
  run_id bigint NOT NULL REFERENCES lean.scrape_runs(id) ON DELETE CASCADE,
  page_number integer NOT NULL CHECK (page_number > 0),
  attempt integer NOT NULL DEFAULT 1 CHECK (attempt > 0),
  fetched_at timestamptz NOT NULL DEFAULT now(),
  request_url text NOT NULL,
  response_state text NOT NULL CHECK (
    response_state IN ('ok', 'verified_empty', 'malformed', 'blocked', 'error')
  ),
  expected_total integer CHECK (expected_total IS NULL OR expected_total >= 0),
  expected_last_page integer CHECK (expected_last_page IS NULL OR expected_last_page > 0),
  response_page integer CHECK (response_page IS NULL OR response_page > 0),
  response_per_page integer CHECK (response_per_page IS NULL OR response_per_page > 0),
  raw_item_count integer NOT NULL DEFAULT 0 CHECK (raw_item_count >= 0),
  parsed_item_count integer NOT NULL DEFAULT 0 CHECK (parsed_item_count >= 0),
  duplicate_item_count integer NOT NULL DEFAULT 0 CHECK (duplicate_item_count >= 0),
  parse_rejection_count integer NOT NULL DEFAULT 0 CHECK (parse_rejection_count >= 0),
  parse_rejections jsonb NOT NULL DEFAULT '[]'::jsonb,
  error text,
  is_authoritative boolean NOT NULL DEFAULT false,
  PRIMARY KEY (run_id, page_number, attempt)
);
CREATE INDEX lean_scrape_run_pages_latest_idx
  ON lean.scrape_run_pages (run_id, page_number, attempt DESC);
CREATE INDEX lean_scrape_run_pages_state_idx
  ON lean.scrape_run_pages (response_state, fetched_at DESC);

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'olx_app') THEN
    GRANT USAGE ON SCHEMA lean TO olx_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON
      lean.neighborhoods, lean.saved_searches, lean.listings,
      lean.price_history, lean.scrape_runs,
      lean.raw_api_responses, lean.scrape_run_pages TO olx_app;
    GRANT SELECT, INSERT ON lean.listing_lifecycle_events TO olx_app;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA lean TO olx_app;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'olx_reporting') THEN
    GRANT USAGE ON SCHEMA lean TO olx_reporting;
    GRANT SELECT ON
      lean.neighborhoods, lean.saved_searches, lean.listings,
      lean.price_history, lean.listing_lifecycle_events,
      lean.scrape_runs, lean.scrape_run_pages TO olx_reporting;
  END IF;
END $$;

COMMIT;
