-- Empty lean archive tables for a fresh database.
CREATE TABLE IF NOT EXISTS lean.raw_api_responses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id bigint REFERENCES lean.scrape_runs(id) ON DELETE SET NULL,
  article_id bigint REFERENCES lean.listings(article_id) ON DELETE SET NULL,
  request_kind text NOT NULL CHECK (request_kind IN ('search', 'detail')),
  request_url text NOT NULL,
  fetched_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT 'infinity'::timestamptz,
  parser_version text NOT NULL,
  payload jsonb,
  source_payload jsonb,
  request_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  response_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  build_version text NOT NULL DEFAULT 'unknown',
  diagnostic jsonb,
  archive_format text NOT NULL DEFAULT 'canonical-v2'
    CHECK (archive_format IN ('canonical-v2', 'diagnostic-v2'))
);
CREATE INDEX IF NOT EXISTS lean_raw_api_responses_stream_idx
  ON lean.raw_api_responses (request_kind, request_url, fetched_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS lean_raw_api_responses_expiry_idx
  ON lean.raw_api_responses (expires_at) WHERE expires_at <> 'infinity';
CREATE INDEX IF NOT EXISTS lean_raw_api_responses_article_idx
  ON lean.raw_api_responses (article_id, fetched_at DESC) WHERE article_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS lean.scrape_run_pages (
  run_id bigint NOT NULL REFERENCES lean.scrape_runs(id) ON DELETE CASCADE,
  page_number integer NOT NULL CHECK (page_number > 0),
  attempt integer NOT NULL DEFAULT 1 CHECK (attempt > 0),
  fetched_at timestamptz NOT NULL DEFAULT now(),
  request_url text NOT NULL,
  response_state text NOT NULL CHECK (
    response_state IN ('ok', 'verified_empty', 'malformed', 'blocked', 'error')
  ),
  expected_total integer CHECK (expected_total IS NULL OR expected_total >= 0),
  expected_last_page integer CHECK (expected_last_page IS NULL OR expected_last_page > 0),
  response_page integer CHECK (response_page IS NULL OR response_page > 0),
  response_per_page integer CHECK (response_per_page IS NULL OR response_per_page > 0),
  raw_item_count integer NOT NULL DEFAULT 0 CHECK (raw_item_count >= 0),
  parsed_item_count integer NOT NULL DEFAULT 0 CHECK (parsed_item_count >= 0),
  duplicate_item_count integer NOT NULL DEFAULT 0 CHECK (duplicate_item_count >= 0),
  parse_rejection_count integer NOT NULL DEFAULT 0 CHECK (parse_rejection_count >= 0),
  parse_rejections jsonb NOT NULL DEFAULT '[]'::jsonb,
  error text,
  is_authoritative boolean NOT NULL DEFAULT false,
  PRIMARY KEY (run_id, page_number, attempt)
);
CREATE INDEX IF NOT EXISTS lean_scrape_run_pages_latest_idx
  ON lean.scrape_run_pages (run_id, page_number, attempt DESC);
CREATE INDEX IF NOT EXISTS lean_scrape_run_pages_state_idx
  ON lean.scrape_run_pages (response_state, fetched_at DESC);
